In [1]:
import os
from tqdm import tqdm
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords
import llm

from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from bertopic.representation import BaseRepresentation
from bertopic.vectorizers import ClassTfidfTransformer
try:
    from cuml.manifold import UMAP
    from cuml.cluster import HDBSCAN
except ImportError:
    from umap import UMAP
    from hdbscan import HDBSCAN

from const import DEFAULT_CHAT_PROMPT, DEFAULT_SYSTEM_PROMPT

ModuleNotFoundError: No module named 'nltk'

In [2]:
df = pd.read_parquet("clean_paragraphs.parquet")
texts = df["TEXT_SPAN"].tolist()
df

,Speech_ID,Paragraph_ID,TEXT_SPAN,role,language_of_text,name
0,81893,81893_p0,La commission propose de ne pas donner suite à...,President,FR,Bugnon André
1,81894,81894_p0,"Ich möchte Sie nur nochmals bitten, das Result...",For the committee,DE,Widmer Hans
2,81894,81894_p1,"In diesem Sinne bitte ich Sie nochmals, den An...",For the committee,DE,Widmer Hans
3,81895,81895_p0,Der Bundesrat beantragt die Annahme des Postul...,Member of the federal council,DE,Schmid Samuel
4,81895,81895_p1,Aber es geht hier noch um andere Fragen. Es ge...,Member of the federal council,DE,Schmid Samuel
...,...,...,...,...,...,...
303379,288681,288681_p11,"En commission, une minorité avait, quant à ell...",For the committee,FR,Python Valentine
303380,288681,288681_p12,La proposition individuelle Bäumle déposée hie...,For the committee,FR,Python Valentine
303381,288681,288681_p13,En ce qui concerne le cas précis de cette prop...,For the committee,FR,Python Valentine
303382,288681,288681_p14,La majorité de la commission désire prendre en...,For the committee,FR,Python Valentine
303383,288681,288681_p15,"Je vous invite donc, au nom de la Commission d...",For the committee,FR,Python Valentine

In [3]:
topic_df = pd.read_csv("240102_bills_swissdomainbert2_predictions.csv")
topic_df

,bill_number,text,date,chamber,domain_id,source,language,time_span_decade,time_span_25y,domain_id_prediction_swissdomainbert2,domain_logits_swissdomainbert2,domain_name_prediction_swissdomainbert2,embeddings_swissdomainbert2,umap_swissdomainbert2
0,...,"Motion der Kommissionsminderheit (Renschier, ....",1987-01-01,Unknown,NaN,graph,DE,1980.0,1975.0,3,"[1.4315958196675638e-07, 8.955157682066783e-05...",Civil Rights,"[-0.6744987368583679, -0.5489828586578369, -0....","[3.0162856578826904, 6.312497615814209]"
1,0.10335,"195. Freymond, vom 26. Juni 1969.Ein ausländis...",1969-06-26,Nationalrat,NaN,graph,DE,1960.0,1950.0,14,"[3.644416892711888e-06, 3.176500104018487e-05,...","Technology, Communication","[0.3503628969192505, -0.17170414328575134, -0....","[6.8938212394714355, 5.891744136810303]"
2,00.001,Der Europarat beging 1999 sein 50-jähriges Bes...,2000-01-12,Ständerat,NaN,graph,DE,2000.0,2000.0,13,"[2.939555633929558e-05, 4.6187258703866974e-05...",International Affairs,"[0.4193879961967468, -0.16224949061870575, 0.2...","[13.971299171447754, -0.31970149278640747]"
3,00.003,In seinem Postulat vom 6. Oktober 1976 beauftr...,2000-01-19,Ständerat,13.0,graph,DE,2000.0,2000.0,13,"[2.9378930776147172e-05, 3.518968151183799e-05...",International Affairs,"[0.42163193225860596, -0.15665242075920105, 0....","[13.986701011657715, -0.2620127201080322]"
4,00.006,Bericht des Bundesrates über seine Geschäftsfü...,2000-03-09,Nationalrat,NaN,graph,DE,2000.0,2000.0,15,"[7.351007297984324e-06, 5.184900146559812e-06,...",Government Operations,"[-0.26835861802101135, -0.4732978343963623, 0....","[-1.9103219509124756, -2.2852351665496826]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89398,zu9711,"Kommission betreffend weiterer Ausbau derETH, ...",1967-08-16,Ständerat,NaN,graph,DE,1960.0,1950.0,7,"[0.019061243161559105, 0.0025766072794795036, ...",Environment,"[-0.12733963131904602, -0.44963544607162476, 0...","[1.1191364526748657, -3.445490598678589]"
89399,zu9765,"79. Kommission für das Arbeitsvertragsrecht,vo...",1969-04-30,Nationalrat,NaN,graph,DE,1960.0,1950.0,5,"[2.07011016755132e-05, 2.7762122044805437e-05,...",Labor,"[0.1266014575958252, 0.058757562190294266, -0....","[0.7178791165351868, 4.478944778442383]"
89400,zu9800,Voranschlag 1968. Nachtrag II. Botschaftund Be...,1968-05-15,Ständerat,NaN,graph,DE,1960.0,1950.0,19,"[0.0478166788816452, 0.0008331555873155594, 0....","Public Finances, Taxation","[-1.7563389539718628, -0.3660387098789215, 0.1...","[6.067897796630859, 10.824517250061035]"
89401,zu9898,"Kommission für die 7. Revision der AHV,vom 10....",1968-09-10,Nationalrat,NaN,graph,DE,1960.0,1950.0,12,"[3.667620660507964e-07, 1.309118033532286e-05,...",Social Welfare,"[-0.5014676451683044, -0.15047380328178406, 0....","[-2.119245767593384, -6.209519386291504]"
89402,zu996,36. Ruhegehalte für die Bundesrate. Antrag auf...,1919-06-12,Nationalrat,NaN,graph,DE,1910.0,1900.0,15,"[0.00022863055346533656, 6.87462670612149e-05,...",Government Operations,"[0.08084304630756378, -0.6872853636741638, 0.0...","[-1.1043742895126343, -2.7381887435913086]"

In [4]:
# Load pre-computed embeddings
embeddings = np.load("paragraph_embeddings.npy")

# Normalize embeddings to unit length
embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
embeddings.shape

(303384, 1024)

In [ ]:
# Hyperparameters for BERTopic
EMBEDDING_MODEL = "BAAI/bge-m3"
RANDOM_SEED = 42
N_SAMPLES = -1
if N_SAMPLES == -1:
    N_SAMPLES = len(texts)

texts_sample = texts[:N_SAMPLES]
embeddings_sample = embeddings[:N_SAMPLES]

print(f"Using {len(texts_sample)} samples for topic modeling.")

bills_topics = topic_df['domain_name_prediction_swissdomainbert2'].unique().tolist()
print(f"Found {len(bills_topics)} unique topics: {bills_topics}")

# UMAP
N_NEIGHBORS = 15
N_COMPONENTS = 5
METRIC = "cosine"

# HDBSCAN
MIN_CLUSTER_SIZE = 300
MIN_SAMPLES = 150
CLUSTER_SELECTION_METHOD = "leaf" # "eom" (excess of mass) or "leaf"

# CounterVectorizer
MIN_DF = 15
MAX_DF = 0.4 # 0.4 means that a term can appear in at most 40% of the documents to be included in the topic representation

# Zero-Shot topic
ZEROSHOT_MIN_SIMILARITY = 0.65 # Min cos similarity between speech embedding and predefined topic embedding to assign the topic to the speech

Using 303384 samples for topic modeling.
Found 21 unique topics: ['Civil Rights', 'Technology, Communication', 'International Affairs', 'Government Operations', 'Economy', 'Education, Research', 'Culture, Arts, Religion, Sport, Entertainment', 'Public Finances, Taxation', 'Agriculture', 'Social Welfare', 'Labor', 'Health', 'National Security, Armed Forces, Defense', 'Environment', 'Energy', '(Public) Transportation', 'Finances, Financial Sector', 'Spatial Planing, Civil Engineering', 'Migration', 'Parliamentary Procedure', 'Criminal Law']

In [6]:
# Load the embedding model
embedder = SentenceTransformer(EMBEDDING_MODEL)

# Download stopwords for German, French, and Italian
nltk.download("stopwords")

# Combine stopwords from German, French, and Italian
stop_words_multi = (
    stopwords.words("german")
    + stopwords.words("french")
    + stopwords.words("italian")
)

# UMAP for dimensionality reduction
umap_model = UMAP(
    n_neighbors=N_NEIGHBORS,
    n_components=N_COMPONENTS,
    metric=METRIC,
    random_state=RANDOM_SEED
)

# HDBSCAN for clustering
hdbscan_model = HDBSCAN(
    min_cluster_size=MIN_CLUSTER_SIZE,
    min_samples=MIN_SAMPLES,
    cluster_selection_method=CLUSTER_SELECTION_METHOD,
    prediction_data=True,
)

# CountVectorizer with custom stop words (German, French, Italian)
vectorizer_model = CountVectorizer(
    stop_words=stop_words_multi,
    min_df=MIN_DF,
    max_df=MAX_DF,  # drops any word appearing in >40% of paragraphs
)
# TF-IDF transformer that reduces the importance of frequent words across topics
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

# Initialize BERTopic with the specified models and parameters
topic_model = BERTopic(
    embedding_model=embedder,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    verbose=True,
    zeroshot_topic_list=bills_topics,
    zeroshot_min_similarity=ZEROSHOT_MIN_SIMILARITY,
)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[nltk_data] Downloading package stopwords to /home/matteo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
overwrite_model = True
if os.path.exists("bertopic_model_raw") and not overwrite_model:
    topic_model = BERTopic.load(
        "bertopic_model_raw",
        embedding_model=embedder,
    )
else:
    print("No model found")

No model found

In [8]:
# Fit model
topics, probs = topic_model.fit_transform(texts_sample, embeddings=embeddings_sample)

2026-04-13 11:05:34,313 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

KeyboardInterrupt:

In [78]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,396,-1_proposition_majorité_initiative_commission,"[proposition, majorité, initiative, commission...","[Le Conseil fédéral, dans les dispositions tra..."
1,0,1,"Finances, Financial Sector","[vertreter, wirtschaftskreise, internen, konsu...","[Die interessierten Wirtschaftskreise, namentl..."
2,1,3,Migration,"[2365, corps, augmentent, auszuschaffen, auszu...",[Der Vertrag erleichtert drittens die Zusammen...
3,2,5,Parliamentary Procedure,"[confirmant, contient, 3bis, adoptées, 152, vo...","[Erste Abstimmung - Premier vote, Erste Abstim..."
4,3,2,"Education, Research","[bildung, forschung, evaluationen, innovation,...","[L'efficacité obtenue dans le domaine ""Formati..."
5,4,15,4_übereinkommen_patrimoine_culturelle_immateri...,"[übereinkommen, patrimoine, culturelle, immate...",[In Übereinstimmung mit dieser Zielsetzung sch...
6,5,12,5_mutilations_génitales_féminines_unbrauchbar,"[mutilations, génitales, féminines, unbrauchba...",[Die Verletzung der weiblichen Genitalien ist ...
7,6,14,6_blutprobe_atemprobe_55_aufwand,"[blutprobe, atemprobe, 55, aufwand, spital, at...",[Nun zum zu behandelnden Artikel 55: Wie soll ...
8,7,10,7_stimmen_antrag_ii_22,"[stimmen, antrag, ii, 22, minderheit, deuxième...",[Für den Antrag der Minderheit I ... 18 Stimme...
9,8,14,8_räumen_raucherbetriebe_öffentlich_passivrauchen,"[räumen, raucherbetriebe, öffentlich, passivra...","[Wenn ich das Wort ergreife, so deshalb, weil ..."
10,9,19,9_arzneimittel_swissmedic_zulassung_arzneimitteln,"[arzneimittel, swissmedic, zulassung, arzneimi...",[Bei diesen Arzneimitteln handelt es sich näml...
11,10,7,10_génération_pilier_transitoire_envisager,"[génération, pilier, transitoire, envisager, p...","[En même temps, et cela fait partie de la stra..."
12,11,22,11_adhérer_zustimmung_nationalrates_beschluss,"[adhérer, zustimmung, nationalrates, beschluss...","[Zustimmung zum Beschluss des Nationalrates, D..."
13,12,8,12_participation_quote_franchise_payer,"[participation, quote, franchise, payer, coûts...",[Je vous rappelle que la participation aux coû...
14,13,27,13_assureurs_versicherten_managed_care,"[assureurs, versicherten, managed, care, versi...",[Die bisherige Erfolgsgeschichte: Seit 1996 kö...
15,14,10,14_hiltpold_jugendverschuldung_jugendlichen_su...,"[hiltpold, jugendverschuldung, jugendlichen, s...",[In der Kommission wurde auch die Auffassung g...
16,15,10,15_registriert_waffen_posteriori_armes,"[registriert, waffen, posteriori, armes, wunsc...",[Sie werden im Rahmen der Waffengesetzrevision...
17,16,26,16_geldwäscherei_terrorismusfinanzierung_gafi_...,"[geldwäscherei, terrorismusfinanzierung, gafi,...",[Eine weitere Diskussion haben wir im Zusammen...
18,17,23,17_nationalbank_staatsfonds_anlagen_risiken,"[nationalbank, staatsfonds, anlagen, risiken, ...",[Der Bundesrat erwartet als Basisszenario kein...
19,18,9,18_dublin_italien_accord_italie,"[dublin, italien, accord, italie, hausaufgaben...","[La seconde motion, 12.3337, a pour but que le..."
20,19,17,19_rola_sanierung_lastwagenfahrer_annahmen,"[rola, sanierung, lastwagenfahrer, annahmen, r...",[Für den San Bernardino haben wir aufgrund der...
21,20,15,20_recherche_forschungsprogrammen_beschaffunge...,"[recherche, forschungsprogrammen, beschaffunge...",[Die Kommission unterstützt zwar das Anliegen ...
22,21,19,21_coopération_österreich_policière_liechtenstein,"[coopération, österreich, policière, liechtens...",[Der trilaterale Polizeivertrag von 1999 zwisc...
23,22,7,22_prescription_délais_verjährungsfrist_vergehen,"[prescription, délais, verjährungsfrist, verge...",[Le premier commence en effet à la fin de la p...
24,23,16,23_abgelehnt_ziffer_massnahme_roland,"[abgelehnt, ziffer, massnahme, roland, büchel,...",[In Artikel 11 ist Ziel 10 fixiert. Es geht um...
25,24,9,24_étrangères_europe_azerbaïdjan_département,"[étrangères, europe, azerbaïdjan, département,...",[Les droits de l'homme sont aussi abordés dans...
26,25,9,25_kantonale_erlassen_vorschriften_strengere,"[kantonale, erlassen, vorschriften, strengere,...","[In der Regel wird darauf verzichtet, in einem..."
27,26,7,26_naturellement_solution_projet_proposons,"[naturellement, solution, projet, proposons, s...",[J'aimerais rappeler que l'avant-projet devrai...
28,27,6,27_statistique_salariales_salariale_inégalités,"[statistique, salariales, salariale, inégalité...",[La mesure de l'inégalité des salaires fait pa...
29,28,5,28_budgets_stratégique_message_orient,"[budgets, stratégique, message, orient, inspir...","[Au fond, la question qui se pose est celle de..."
30,29,32,29_référendum_dépenses_finanzreferendums_finan...,"[référendum, dépenses, finanzreferendums, fina...",[Ich möchte Sie noch auf einen Hauptpunkt der ...
31,30,10,30_ferien_arbeitnehmer_wochen_anspruch,"[ferien, arbeitnehmer, wochen, anspruch, stres...",[Der Bundesrat beantragt Ihnen zusammen mit de...
32,31,6,31_minimale_durée_séjour_obergrenze,"[minimale, durée, séjour, obergrenze, canton, ...","[Wenn Sie trotzdem der Meinung sind, dass Sie ..."
33,32,11,32_naturalisation_einbürgerung_facilitée_erlei...,"[naturalisation, einbürgerung, facilitée, erle...","[Nun zur erleichterten Einbürgerung, die Herr ..."
34,33,25,33_délibérations_juges_tribunal_urteilsberatungen,"[délibérations, juges, tribunal, urteilsberatu...",[Nous craignons tout d'abord un risque de pres...
35,34,8,34_autorisation_commerce_police_piétons,"[autorisation, commerce, police, piétons, stra...",[Für mich ist es immer spannend zu hören - auc...
36,35,10,35_alter_helmtragpflicht_kinder_helmpflicht,"[alter, helmtragpflicht, kinder, helmpflicht, ...",[Herr Nationalrat Binder hat natürlich Recht: ...
37,36,7,36_verkehrssicherheit_sicherheit_aspekten_fuss...,"[verkehrssicherheit, sicherheit, aspekten, fus...","[Es geht nicht darum, Gemeinden oder Kantone z..."
38,37,10,37_rückwirkung_ungültig_demokratie_grundprinzi...,"[rückwirkung, ungültig, demokratie, grundprinz...","[Es ist natürlich nicht so, dass wir die Frage..."
39,38,5,38_märz_ordnungsantrag_nahm_2013,"[märz, ordnungsantrag, nahm, 2013, kommissions...",[Das Bundesgesetz über eine Anpassung des Gese...
40,39,8,39_bericht_auslandbürgerinnen_demokratisch_ver...,"[bericht, auslandbürgerinnen, demokratisch, ve...","[Ich möchte nochmals festhalten, weil das offe..."
41,40,6,40_portmann_willy_danken_garderobier,"[portmann, willy, danken, garderobier, beau, a...",[Im Namen des Parlamentes sende ich die besten...
42,41,8,41_steuern_mechanismus_unternehmenssteuerrefor...,"[steuern, mechanismus, unternehmenssteuerrefor...",[Mit dieser Annahme wirft der Initiant den Kan...
43,42,5,42_abzüge_gewinne_gestehungskosten_teilbesteue...,"[abzüge, gewinne, gestehungskosten, teilbesteu...",[Seit dem Jahr 1948 mit der Einführung der AHV...
44,43,5,43_ch_abs_ziff_gesetzgeberischen,"[ch, abs, ziff, gesetzgeberischen, art, commun...",[Eine Annahme dieser Initiative hätte die folg...
45,44,17,44_vorläufige_commissions_anwendung_kommissionen,"[vorläufige, commissions, anwendung, kommissio...",[Man hat mittlerweile über eine ganze Palette ...
46,45,17,45_abzulehnen_argumentation_ausführung_tenor,"[abzulehnen, argumentation, ausführung, tenor,...","[Ich bitte Sie daher, den Minderheitsantrag be..."
47,46,10,46_voix_1560_minder_optant,"[voix, 1560, minder, optant, jositsch, eingesc...","[La commission vous recommande donc, par 19 vo..."
48,47,12,47_recommande_voix_décision_13,"[recommande, voix, décision, 13, maintenir, et...","[Voilà, c'est par 13 voix contre 10 que votre ..."
49,48,17,48_lade_einzutreten_namen_anzubringen,"[lade, einzutreten, namen, anzubringen, bundes...","[Damit lade ich Sie ein, auf die Vorlage einzu..."
50,49,28,49_folgen_bitte_mehrheit_zuzustimmen,"[folgen, bitte, mehrheit, zuzustimmen, arroseu...","[Ich bitte Sie, hier auch der Mehrheit Ihrer K..."

In [79]:
topic_model.visualize_topics()

In [80]:
top_n = 20
topic_model.visualize_heatmap(top_n_topics=top_n, title=f"Top {top_n} Topics Heatmap")

In [66]:
topics_per_class = topic_model.topics_per_class(texts_sample, df.iloc[:N_SAMPLES]["name"])

55it [00:00, 112.15it/s]

In [67]:
topic_model.visualize_topics_per_class(topics_per_class)

In [ ]:
# Save model
topic_model.save(
    path="bertopic_model_raw",
    serialization="safetensors",
    save_embedding_model=True,
    save_ctfidf=True,
)

In [68]:
topic_info = topic_model.get_topic_info()
valid_topics = topic_info[topic_info["Topic"] != -1]
valid_topics

,Topic,Count,Name,Representation,Representative_Docs
1,0,34,0_référendum_dépenses_finanzreferendums_finanz...,"[référendum, dépenses, finanzreferendums, fina...",[Ich möchte Sie noch auf einen Hauptpunkt der ...
2,1,28,1_geldwäscherei_gafi_terrorismusfinanzierung_e...,"[geldwäscherei, gafi, terrorismusfinanzierung,...",[Herr Kollege Schweiger hat es bereits gesagt....
3,2,26,2_délibérations_juges_tribunal_urteilsberatungen,"[délibérations, juges, tribunal, urteilsberatu...",[Nous craignons tout d'abord un risque de pres...
4,3,24,3_versicherten_assureurs_versicherer_ärzte,"[versicherten, assureurs, versicherer, ärzte, ...","[Pour toute entreprise, la prévisibilité est l..."
5,4,23,4_steuern_nfa_mechanismus_unternehmenssteuerre...,"[steuern, nfa, mechanismus, unternehmenssteuer...",[Seit dem Jahr 1948 mit der Einführung der AHV...
6,5,22,5_nationalbank_staatsfonds_anlagen_task,"[nationalbank, staatsfonds, anlagen, task, ris...",[Der Bundesrat erwartet als Basisszenario kein...
7,6,22,6_coopération_österreich_policière_liechtenstein,"[coopération, österreich, policière, liechtens...",[Der trilaterale Polizeivertrag von 1999 zwisc...
8,7,20,7_vorläufige_differenzbereinigungsverfahren_an...,"[vorläufige, differenzbereinigungsverfahren, a...",[Man hat mittlerweile über eine ganze Palette ...
9,8,19,8_arzneimittel_swissmedic_zulassung_arzneimitteln,"[arzneimittel, swissmedic, zulassung, arzneimi...",[Bei diesen Arzneimitteln handelt es sich näml...
10,9,19,9_lade_einzutreten_namen_abs,"[lade, einzutreten, namen, abs, branchenlösung...",[Bei der Behandlung dieses Artikels möchte ich...
11,10,17,10_adhérer_zustimmung_nationalrates_entwurf,"[adhérer, zustimmung, nationalrates, entwurf, ...","[Adhérer à la décision du Conseil national, Ad..."
12,11,17,11_abgelehnt_ziffer_massnahme_büchel,"[abgelehnt, ziffer, massnahme, büchel, roland,...",[In Artikel 11 ist Ziel 10 fixiert. Es geht um...
13,12,16,12_folgen_bitte_arroseur_vorstössen,"[folgen, bitte, arroseur, vorstössen, mehrheit...","[Ich bitte Sie namens der Kommission, bei beid..."
14,13,15,13_considérons_rejeter_argumentation_dénuée,"[considérons, rejeter, argumentation, dénuée, ...",[Aus diesem Grund beantragen wir Ihnen die Abl...
15,14,15,14_übereinkommen_patrimoine_culturelle_immater...,"[übereinkommen, patrimoine, culturelle, immate...",[In Übereinstimmung mit dieser Zielsetzung sch...
16,15,14,15_blutprobe_atemprobe_55_aufwand,"[blutprobe, atemprobe, 55, aufwand, beweissich...",[Nun zum zu behandelnden Artikel 55: Wie soll ...
17,16,13,16_recommande_voix_décision_13,"[recommande, voix, décision, 13, contre, maint...","[Voilà, c'est par 13 voix contre 10 que votre ..."
18,17,13,17_räumen_raucherbetriebe_öffentlich_passivrau...,"[räumen, raucherbetriebe, öffentlich, passivra...","[Wenn ich das Wort ergreife, so deshalb, weil ..."
19,18,12,18_recherche_innovation_forschung_bildung,"[recherche, innovation, forschung, bildung, na...",[Die Kommission unterstützt zwar das Anliegen ...
20,19,12,19_vote_abstimmung_stimmen_antrag,"[vote, abstimmung, stimmen, antrag, ii, 22, mi...","[Zweite Abstimmung - Deuxième vote, Für den An..."
21,20,12,20_hiltpold_jugendlichen_jugendverschuldung_su...,"[hiltpold, jugendlichen, jugendverschuldung, s...",[An der Sitzung vom 14. Mai 2013 hat die WAK e...
22,21,12,21_rückwirkung_materie_einheit_ungültig,"[rückwirkung, materie, einheit, ungültig, zwec...","[Es wurde im Gutachten Glauser, das ja immer w..."
23,22,12,22_registriert_posteriori_waffen_armes,"[registriert, posteriori, waffen, armes, wunsc...",[Sie werden im Rahmen der Waffengesetzrevision...
24,23,12,23_mutilations_génitales_féminines_unbrauchbar,"[mutilations, génitales, féminines, unbrauchba...",[Die Verletzung der weiblichen Genitalien ist ...
25,24,12,24_ferien_arbeitnehmer_wochen_anspruch,"[ferien, arbeitnehmer, wochen, anspruch, stres...",[Der Bundesrat beantragt Ihnen zusammen mit de...
26,25,11,25_dublin_italie_italien_accord,"[dublin, italie, italien, accord, schengen, gr...","[La seconde motion, 12.3337, a pour but que le..."
27,26,11,26_kantonale_erlassen_vorschriften_strengere,"[kantonale, erlassen, vorschriften, strengere,...",[Eine letzte Bemerkung: Ist das Gesetz notwend...
28,27,11,27_naturellement_projet_solution_juridiques,"[naturellement, projet, solution, juridiques, ...",[Je vous propose d'entrer en matière sur ce pr...
29,28,11,28_alter_helmtragpflicht_kinder_eigenverantwor...,"[alter, helmtragpflicht, kinder, eigenverantwo...",[Herr Nationalrat Binder hat natürlich Recht: ...
30,29,11,29_autorisation_piétons_commerce_police,"[autorisation, piétons, commerce, police, pass...",[C'est dire que l'autorisation de construire e...
31,30,10,30_lastwagen_lastwagenfahrer_sanierung_rola,"[lastwagen, lastwagenfahrer, sanierung, rola, ...",[Für den San Bernardino haben wir aufgrund der...
32,31,10,31_étrangères_bons_suisse_offices,"[étrangères, bons, suisse, offices, consultati...","[Entre-temps, il est devenu clair que la Suiss..."
33,32,10,32_finanzplatzes_lage_indikatoren_adäquat,"[finanzplatzes, lage, indikatoren, adäquat, si...","[Diese ""Too big to fail""-Regelung geht weiter ..."
34,33,9,33_quorum_schriftlicher_mitglieder_3765,"[quorum, schriftlicher, mitglieder, 3765, zust...","[Von daher möchte ich Sie bitten, bei Absatz 1..."
35,34,9,34_naturalisation_einbürgerung_facilitée_erlei...,"[naturalisation, einbürgerung, facilitée, erle...","[Nun zur erleichterten Einbürgerung, die Herr ..."
36,35,9,35_atteindre_brut_aide_2015,"[atteindre, brut, aide, 2015, revenu, budgets,...","[Monsieur Vitali, permettez-moi de vous dire q..."
37,36,9,36_coûts_participation_payer_quote,"[coûts, participation, payer, quote, franchise...",[Je vous rappelle que la participation aux coû...
38,37,8,37_willy_beifall_portmann_altershalber,"[willy, beifall, portmann, altershalber, geran...",[Ce président peut vous dire aussi que nous av...
39,38,8,38_buchstabe_ordnungsantrag_galladé_examiner,"[buchstabe, ordnungsantrag, galladé, examiner,...",[Die Kommission schloss sich einstimmig den Sc...
40,39,8,39_fussgängerstreifen_sicherheit_verkehrssiche...,"[fussgängerstreifen, sicherheit, verkehrssiche...","[Es geht nicht darum, Gemeinden oder Kantone z..."
41,40,8,40_prescription_vergehen_délais_verjährungsfri...,"[prescription, vergehen, délais, verjährungsfr...",[Bei Absatz 2 sieht die Kommission vor allem a...
42,41,7,41_auslandbürgerinnen_demokratisch_vertretung_...,"[auslandbürgerinnen, demokratisch, vertretung,...",[Warum ist dieses Thema eigentlich von Bedeutu...
43,42,6,42_minimale_durée_séjour_obergrenze,"[minimale, durée, séjour, obergrenze, canton, ...","[Wenn Sie trotzdem der Meinung sind, dass Sie ..."
44,43,6,43_uhr_09_00_session,"[uhr, 09, 00, session, borer, ordnungsantrag, ...",[Schluss der Sitzung und der Session um 09.00 ...
45,44,6,44_1560_rallier_évoquer_eingeschwenkt,"[1560, rallier, évoquer, eingeschwenkt, josits...","[Pour ces raisons, la commission a rejeté la p..."
46,45,6,45_steuerverwaltung_baubeginns_pauschalpreises...,"[steuerverwaltung, baubeginns, pauschalpreises...",[Im Verhältnis zur zivilrechtlichen Unterschei...
47,46,6,46_modifiziertem_adoptées_adopté_fiel,"[modifiziertem, adoptées, adopté, fiel, angeno...",[Adopté selon la proposition modifiée de la co...
48,47,6,47_leitlinie_positionieren_aeschi_norwegen,"[leitlinie, positionieren, aeschi, norwegen, i...",[Zu den Fragen betreffend das Verhältnis der S...
49,48,6,48_statistique_salariales_salariale_inégalités,"[statistique, salariales, salariale, inégalité...",[La mesure de l'inégalité des salaires fait pa...
50,49,6,49_schwelle_grenzregion_marktverzerrung_untern...,"[schwelle, grenzregion, marktverzerrung, unter...","[Zur zweiten Frage, die in allen Details anges..."
51,50,6,50_génération_pilier_envisager_transitoire,"[génération, pilier, envisager, transitoire, p...","[En même temps, et cela fait partie de la stra..."
52,51,5,51_300_revenus_steuertarifen_progressif,"[300, revenus, steuertarifen, progressif, eink...","[Par son initiative parlementaire, Monsieur Zi..."
53,52,5,52_compensation_risques_correction_décidée,"[compensation, risques, correction, décidée, k...","[Jusqu'à il y a peu de temps, un an et demi à ..."
54,53,5,53_minderheitsanträge_borer_beziehungsweise_ab...,"[minderheitsanträge, borer, beziehungsweise, a...","[Ich bitte Sie wirklich, hier der Mehrheit Ihr..."
55,54,5,54_insieme_teilnehmerkreis_it_government,"[insieme, teilnehmerkreis, it, government, sta...","[Zuerst zu Artikel 2 Ziffer 1, zur Frage der A..."
56,55,5,55_zahlen_abgeltungssteuerabkommen_marktzutrit...,"[zahlen, abgeltungssteuerabkommen, marktzutrit...","[Ein weiterer Punkt: Sie haben bemerkt, dass z..."

Qwen LLM topic description refinement

In [ ]:
# class QwenTopic(BaseRepresentation):
#     def __init__(
#         self,
#         model: str = "sdsc-qwen-32b",
#         prompt=DEFAULT_CHAT_PROMPT,
#         system_prompt=DEFAULT_SYSTEM_PROMPT,
#         nr_docs: int = 4,
#         diversity: float | None = None,
#         **kwargs,
#     ):
#         """
#         Use Qwen to extract topic labels from a set of documents and keywords.

#         Arguments:
#             model: The Qwen model to use (e.g., "sdsc-qwen-32b")
#             prompt: The prompt template to use for Qwen. It should contain [KEYWORDS] and/or [DOCUMENTS] as placeholders.
#             system_prompt: The system prompt to set the behavior of the Qwen model.
#             nr_docs: The number of documents to pass if a prompt
#                  with the `["DOCUMENTS"]` tag is used.
#             diversity: Accepts values between 0 and 1. A higher
#                    values results in passing more diverse documents
#                    whereas lower values passes more similar documents.
#         """
#         self.model = model
#         self.prompt = prompt
#         self.system_prompt = system_prompt
#         self.nr_docs = nr_docs
#         self.diversity = diversity

#         self.prompts_ = []

#     def extract_topics(self, topic_model, documents, c_tf_idf, topics):
#         """Extract topics

#         Arguments:
#             topic_model: The BERTopic model
#             documents: A dataframe of documents with their related topics
#             c_tf_idf: The c-TF-IDF matrix
#             topics: The candidate topics as calculated with c-TF-IDF

#         Returns:
#             updated_topics: Updated topic representations
#         """
#         repr_docs_mappings, _, _, _ = topic_model._extract_representative_docs(
#             c_tf_idf, documents, topics, 500, self.nr_docs, self.diversity
#         )

#         updated_topics = {}
#         for topic, docs in tqdm(
#             repr_docs_mappings.items(), disable=not topic_model.verbose
#         ):
#             prompt = self._create_prompt(docs, topic, topics)
#             self.prompts_.append(prompt)

#             qwen_model = llm.get_model(self.model)
#             response = qwen_model.prompt(prompt=prompt, system=self.system_prompt)
#             answer = response.text()
#             after_thinking = answer.split("</think>")[-1]
#             label = after_thinking.replace("topic:", "").strip()
#             updated_topics[topic] = [(label, 1)]

#         return updated_topics

#     def _create_prompt(self, docs, topic, topics):
#         keywords = next(zip(*topics[topic]))

#         # Use the Default Chat Prompt
#         if self.prompt == DEFAULT_CHAT_PROMPT:
#             prompt = self.prompt.replace("[KEYWORDS]", ", ".join(keywords))
#             prompt = self._replace_documents(prompt, docs)

#         # Use a custom prompt that leverages keywords, documents or both using
#         # custom tags, namely [KEYWORDS] and [DOCUMENTS] respectively
#         else:
#             prompt = self.prompt
#             if "[KEYWORDS]" in prompt:
#                 prompt = prompt.replace("[KEYWORDS]", ", ".join(keywords))
#             if "[DOCUMENTS]" in prompt:
#                 prompt = self._replace_documents(prompt, docs)

#         return prompt

#     @staticmethod
#     def _replace_documents(prompt, docs):
#         to_replace = ""
#         for doc in docs:
#             to_replace += f"- {doc}\n"
#         prompt = prompt.replace("[DOCUMENTS]", to_replace)
#         return prompt

#     def get_prompts(self):
#         """Returns the prompts used for topic extraction."""
#         return self.prompts_

In [ ]:
llm_labels = {}
qwen_model = llm.get_model("sdsc-qwen-32b")

In [ ]:
for _, row in tqdm(valid_topics.iterrows(), total=len(valid_topics)):
    topic_id = row["Topic"]
    keywords = row["Representation"]
    rep_docs = row["Representative_Docs"][:3]

    prompt = DEFAULT_CHAT_PROMPT.replace("[KEYWORDS]", ", ".join(keywords))
    docs_text = "\n".join([f"- {doc}" for doc in rep_docs])
    prompt = prompt.replace("[DOCUMENTS]", docs_text)

    try:
        response = qwen_model.prompt(prompt=prompt, system=DEFAULT_SYSTEM_PROMPT)
        answer = response.text().split("</think>")[-1]
        label = answer.replace("topic:", "").strip()
        llm_labels[topic_id] = label
    except Exception as e:
        print(f"Failed on topic {topic_id}: {e}")
        llm_labels[topic_id] = "ERROR"